# Generated by Django 5.1.3 on 2024-11-28 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('health_status', models.BooleanField(default=True)),
                ('weight', models.FloatField()),
                ('temperature', models.FloatField()),
                ('blood_type', models.CharField(max_length=10)),
                ('blood_quantity', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
